version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  web-app:
    build:
      context: ./luxonis
      dockerfile: Dockerfile_web
    container_name: my-web-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  scrapy-app:
    build:
      dockerfile: Dockerfile
    container_name: my-scrapy-app
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge